# Note: Need both NerdFont AND Emoji support.

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

right_format = "$cmd_duration"

[character] 
success_symbol = "[➜](bold green)"

# Disable the package module, hiding it from the prompt completely
[battery]
disabled = true

[status]
disabled = false
symbol = " "

[directory]
repo_root_style = "yellow dimmed"

[cmd_duration]
format = "[$duration]($style)"
show_milliseconds = false
show_notifications = false

[git_metrics]
disabled = true

[git_status]
format = "([$ahead_behind ]($style))"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
