local augroup = vim.api.nvim_create_augroup("ClangAutoFmt", {})

local clangformat_config = [[
# Generated by my nvim config, do not edit manually.
BasedOnStyle: LLVM
IndentWidth: 4
AllowShortFunctionsOnASingleLine: Empty # Prevents oneliner function
IndentPPDirectives: AfterHash
QualifierAlignment: Left
]]

local function write_clangformat_config()
	local file = io.open(vim.fn.expand("~/.clang-format"), "w")
	if file then
		file:write(clangformat_config)
		file:close()
	else
		vim.notify("Unable to initialize ~/.clang-format", vim.log.levels.ERROR)
	end
end
write_clangformat_config()

return function(capabilities)
	capabilities["offsetEncoding"] = "utf-8"
	return {
		clangd = {
			capabilities = capabilities,
		},
	}
end
