#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selection=$1
else
	choices=$(find ~/ledr ~/dz -mindepth 1 -maxdepth 1 -type d)
	choices=$(echo "$choices" | sed "s|$HOME/||")

	choices=$(echo -e "root\n$choices")
	selection=$(echo "$choices" | tofi)
	if [[ -z $selection ]]; then
		exit 0
	fi
	selection="$HOME/$selection"
fi

selection_name=$(basename "$selection" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selection_name -c $selection
    exit 0
fi

if ! tmux has-session -t=$selection_name 2> /dev/null; then
    tmux new-session -ds $selection_name -c $selection
fi

tmux switch-client -t $selection_name
