local lspconfig = require('lspconfig')
local M = {}

local augroup = vim.api.nvim_create_augroup("ClangAutoFmt", {})

local clangformat_config = [[
# Generated by my nvim config, do not edit manually.
BasedOnStyle: LLVM
IndentWidth: 4
AllowShortFunctionsOnASingleLine: Empty # Prevents oneliner function
IndentPPDirectives: AfterHash
QualifierAlignment: Left
]]

local function write_clangformat_config()
	local file = io.open(vim.fn.expand('~/.clang-format'), "w")
	if file then
		file:write(clangformat_config)
		file:close()
	else
		vim.notify("Unable to initialize ~/.clang-format", vim.log.levels.ERROR)
	end
end
write_clangformat_config()

M.setup = function(capabilities)
	capabilities['offsetEncoding'] = 'utf-8'
	lspconfig.clangd.setup {
		capabilities = capabilities,
		on_attach = function (_, bufnr)
			vim.api.nvim_create_autocmd("BufWritePre", {
				group = augroup,
				buffer = bufnr,
				callback = function()
					vim.lsp.buf.format({ bufnr = bufnr })
				end
			})
		end
}
end

return M

